### ISSUE TITLE
Logs are not disappearing at set time

### ISSUE THREAD

**Issue by kyleknighted** [fabien-d/alertify.js#103]
I have code that looks like  
`alertify.log( data.name + ' has disconnected!', 'error', 5000 )`

The problem is, it is not disappearing after 5 seconds.  
It just sits there forever.

Also, if I click on the log, it will not disappear either.

No JavaScript errors in console.

Running Alertify 0.3.6 on Chrome 23.0.1271.101 on Mac OS X

**Comment by fabien-d** [comment]
Strange... can you try pasting the following in the console on http://fabien-d.github.com/alertify.js/ and see if you can reproduce?

``` js
data = { name: "test" }
alertify.log(data.name + ' has disconnected!', 'error', 5000);
```

or using the `error` shorthand.

``` js
data = { name: "test" }
alertify.error(data.name + ' has disconnected!', 5000);
```

I've tried both in chrome on OS X and don't have an issue clicking to close, or changing the `5000` to any value.

**Comment by kyleknighted** [comment]
I tried using the `alertify.error(data.name + ' has disconnected!', 5000);` method, but that's not working either.
I'm assuming there is a conflict with my other micro-libs I am using.

I followed the URL you linked to, but I do not see an interactive console for me to paste anything into. But your example Log messages at the bottom work as expected.

**Comment by fabien-d** [comment]
If you're using chrome.. you can hit `cmd+alt+j` to pull up the console or View > Developer > JavaScript Console. You'll be able to use the console there.

But it does sound like a conflict... if you have a hard time debugging, you can post (or send me a DM) with more code, I can take a look.

**Comment by kyleknighted** [comment]
Ah, that console. Sorry. I was thinking you had some type of interactive 
console on the website...

I realized it wasn't the JavaScripts fault.
I didn't update to the newer CSS. So, none of the transitions were firing.

Thanks for the help!

Fabien Doiron wrote:

**Comment by fabien-d** [comment]
No problem, glad you were able to sort it out.
