### ISSUE TITLE
alert display, one by one

### ISSUE THREAD

**Issue by jduval** [fabien-d/alertify.js#108]
User submit form, it shows alert. If the user quickly re submit, currently, it will show other alerts  over the first.

Can I stop new alert's display during the first alert's display?

**Comment by fabien-d** [comment]
Could you provide a code sample (reproducible example)? Currently alertify dialogs are queued and shouldn't overlap. Also, the cover element should show up blocking any interaction with the page. I'm attempting to double click buttons on the example site and can't encounter the issue.

Is there a JS error? There could be a conflict.

As a side note, something to consider. A user shouldn't be able to re-submit a form.

**Comment by jduval** [comment]
I didn't express myself as I meant to. Your great plugin works very well ;) no JS error.

But if user click a lot of time on submit button, it's like it:
![alertify](https://f.cloud.github.com/assets/1597299/93060/147495c8-660b-11e2-8a67-7a37347cf0e7.jpg)

So my question is : can I stop error's display if there is already the same one on screen?

**Comment by fabien-d** [comment]
> it will show other alerts

My bad, I misunderstood this part. I was thinking dialogs and not log messages.

For log messages, currently there is no way to only open them once, or only if they are not currently open. The thought behind logs was always a 1:1, every time you take an action the corresponding log is shown.

I feel like multiple log messages is still better than no logs at all. That way a user is aware that he's taken another action. If a user clicks a button and there's a log tied to it, then it should show a new one every time that button is clicked. If you don't want it to show more than once, the button should get disabled.

A form for example, I still believe the best approach is to disable the submit button until the form action is completed.

I personally feel like removing the log notification is a workaround the problem... and not really a solution to the problem.

**Comment by jduval** [comment]
yep... that was I suppose... maybe I missed something in params... but ok.

thanks for your ans and your great app!

cheers!

**Comment by svrabl** [comment]
if($('.alertify-log').length > 0){
    $('.alertify-log').css('display', 'none');
}
alertify.log("New message");
