### ISSUE TITLE
Dialog boxes are not modal

### ISSUE THREAD

**Issue by fkautz** [fabien-d/alertify.js#12]
Alerts are currently a box that pops up above the main text. Users can still interact with the main page (and do so by default). However, focus is set to the underlying page.

If possible, can the dialog boxes be modal where focus to the dialog box is stronger or enforced? E.g. In chrome, hitting space when looking at a dialog box scrolls down instead of dismissing the box. Hitting enter works as expected and dismisses the dialog box.

**Comment by abrkn** [comment]
it says unobtrusive in the description. modal is obtrusive

**Comment by fkautz** [comment]
I don't see how a dialog box can be unobtrusive, it sits prominently above everything else. :)

Anyways, what triggered this was alert and confirm boxes can be dismissed by an enter key but not by hitting the spacebar. Maybe it's related to the focus issue listed in issue #3.

**Comment by fabien-d** [comment]
Closing with ^ pull request
