### ISSUE TITLE
alertify delay

### ISSUE THREAD

**Issue by fabien-d** [fabien-d/alertify.js#125]
> alertify.set({ delay: 10000 });
> Gratitude for your masterpiece, but I wonder if the "Notification" holding 10 seconds could be an active decounting animation? Grateful for your reply...

Question was originally posted by @Martinho0330 in a PR so opening as a new issue

**Comment by fabien-d** [comment]
@Martinho0330: Could you be more specific? I'm not sure exactly what you mean?

**Comment by Martinho0330** [comment]
@fabien-d  Er,,,I mean When I set up a 10s delay log message dialog, it will hide after 10 seconds passes, but during this 10 seconds, could I make the amount 10 decrease from 10 to 1 as a Timer ?

**Comment by Martinho0330** [comment]
@fabien-d Sorry to bother you at such a early morning, I've forgotten that you were in the EST area....

**Comment by fabien-d** [comment]
If I understand correctly, you want to display the text as it goes down? e.g. 10... 9... 8... until the notification is closed?

If that's the case, you cannot. The new version `0.4.0rc1`, not yet stable, does offer an API to the log elements, so it's something that could be added on your end.

``` js
// using 0.4.0rc1
// this will not work with 0.3.8
var log = Alertify.log.info("Notification Message", 10000);

// will return the log DOM element which you can manipulate
console.log(log.el);
```

**Comment by Martinho0330** [comment]
@fabien-d I see. Thanks a lot for your kindness.
