### ISSUE TITLE
Any way to make it working in (IE9) "Compatibility" mode?

### ISSUE THREAD

**Issue by vkelman** [fabien-d/alertify.js#126]
I downloaded a stable version and tried 

``` js
 alertify.set({ labels: {ok: "Accept", cancel : "Deny"} });
 alertify.confirm("Confirm dialog with custom button labels", function (e) {
 if (e) { alertify.success("You've clicked OK"); }
 else { alertify.error("You've clicked Cancel"); }
```

In IE9 in compatibility mode a dialog displays only the left button, until you hover a mouse over the place right button is supposed to be.  In IE standard mode it works fine (and works fine in Chrome.)

**Comment by fabien-d** [comment]
I'll have investigate this one. I'm currently away at a conference but will take a look when I get back. 

Any reason why you're running compatibility mode? Just curious!

**Comment by vkelman** [comment]
Pretty stupid reason: we have a big "legacy" web site which was designed
for earlier versions of IE and doesn't want to work correctly in a standard
mode of modern IE. Yes, we should update it, but we don't have enough
resources.

Vladimir Kelman
http://www.google.com/profiles/vkelman

**Comment by fabien-d** [comment]
I got to test it and was able to recreate the issue.

![Compatibility](https://f.cloud.github.com/assets/747616/205365/1e003820-81a6-11e2-820c-63a8e45edcca.png)

It's something to do with the `:focus` state. If you hit the tab key to cycle through the button, whichever one has focus doesn't show. First thing you could try is to remove the `:focus` state in the CSS. See if that works.

I'll will look at it this weekend, just don't have time while at the conference to debug.

Cheers,

**Comment by fabien-d** [comment]
I just tested the 0.4.0 release candidate version - tag `0.4.0rc1` and it works. I'll sort out what the differences are between the 2 and get a fix in for the `0.3.*` stable release. 0.3.\* will be deprecated shortly as 0.4.0 approaches.

![Compatibility0 4 0rc1](https://f.cloud.github.com/assets/747616/206580/0e9483cc-81d4-11e2-8f23-3c1e3db7f250.png)

**Comment by vkelman** [comment]
Fabien,

Thank you, I really appreciate your responsiveness. Forgive my ignorance,
I'm not familiar enough with GitHub, but can I simply download ver. 0.4.0
or should I somehow Clone etc. ?

Vladimir Kelman
http://www.google.com/profiles/vkelman

**Comment by fabien-d** [comment]
You can grab the source [on the tags page](https://github.com/fabien-d/alertify.js/tags).

Just a word of warning, 0.4.0rc1 is a release candidate, so everything may not be stable, and also the API has changed quite a bit from 0.3.*.

Feel free to look at the demo site at http://fabien-d.github.com/alertify.js/0.4.0rc1

**Comment by fabien-d** [comment]
Fixed with ^ PR

**Comment by diviti** [comment]
Hi. Had a similar problem on 0.3.10. Also legacy code ... ;) Alertify bar was positioned on the left side, buttons not visible. <!doctype html> was missing before <html> tag. Including it in doc resolved problem ...
