### ISSUE TITLE
0.3.8: Recusion causing unintuitive behaviour

### ISSUE THREAD

**Issue by ysangkok** [fabien-d/alertify.js#127]
I asked a [StackOverflow question](http://stackoverflow.com/q/15125537/309483) about this. I'd like to know what I'm supposed to get the desired behaviour, I think the setTimeout is a hack. And i'm not convinced it's a browser bug, yet.

Thanks in advance for your patience.

**Comment by fabien-d** [comment]
I'll be investigating this. The answer provided does makes sense (as a workaround) since `transitionend` can be a bit buggy. I will try to find a more elegant solution to include as part of alertify.

**Comment by fabien-d** [comment]
Closing this issue - if it's still a problem feel free to reopen or open a new issue.
