### ISSUE TITLE
animation doesn't work on IE9

### ISSUE THREAD

**Issue by SeaHawk** [fabien-d/alertify.js#129]
animation for logs and dialogs doesn't work on IE9.

**Comment by fabien-d** [comment]
You have to provide more information in order for someone to help you out. You should check the [opening issues wiki entry](https://github.com/fabien-d/alertify.js/wiki/Opening-Issues)

## Short version of the wiki entry
- Please list the exact steps required to reproduce the issue.
- Include versions of your OS, browser, etc.
- Include relevant sample code. The less code you include, the easier/faster the problem can be found. Try to only include the bare minimum code required to reproduce the error.

**Comment by fabien-d** [comment]
See [caniuse](http://caniuse.com/css-transitions) and [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transitions?redirectlocale=en-US&redirectslug=CSS%2FTutorials%2FUsing_CSS_transitions#Browser_compatibility)
