### ISSUE TITLE
Repeated display

### ISSUE THREAD

**Issue by jjsaunier** [fabien-d/alertify.js#134]
My version is 0.3.8 (lastest stable) for Alertify and jQuery 1.9

I will try explain you the problem.

So, when you use the following code : 

```
    $("#element").on("change", function(){
       callback($(this));
    });

    function callback($object){
       alertify.success("Hello world");
    }
```

If you change the value of select input type, alertify will take a weird behaviour. He count how many times you change her value, and when he will displaying the message box, several message will appear, proportionally at the count of you change the statement of select box

**Comment by fabien-d** [comment]
I'm not really sure what the issue is - any chance you could provide a working code sample of the issue?

**Comment by georaldc** [comment]
If you're talking about the stacking messages, I believe that is its normal behavior

**Comment by jjsaunier** [comment]
I have tried to repeat the bug on jsFiddle, impossible. And i have found the issue (on my side), some js code before this make this behaviour.

@georaldc nope, when i triggered the event, that stack 4 messages box in same time. In normal case it's one event trigerred equal one message.

So it's not a bug.
