### ISSUE TITLE
Ok/Cancel buttons' anchor links work occasionally, despite preventDefault.

### ISSUE THREAD

**Issue by sivasankari88** [fabien-d/alertify.js#139]
Hi,

We are using alertify 0.3.8, and this is the code that we use.

```
function(event) {
        event.preventDefault();
        alertify.set({ buttonFocus: 'cancel'});
        alertify.confirm('Message',
                function(flag) {
            if (flag) {
                // Code here
            }
        });
        return false;
    }
```

The event is either from a button or anchor element. In most of the cases, clicking the alertify's buttons work fine. Occasionally, clicking Ok/Cancel button takes us to the top of the page and # gets appended to the URL. Is there a way to prevent this behavior? 

Also at times, link style is applied to 'Cancel' button as shown in the screen shot. 
![screenshot](https://f.cloud.github.com/assets/1781288/542303/758c85ba-c221-11e2-8eaa-1394fb679766.png)

This issue occurs only occasionally and it will be helpful if there is a workaround or a fix for this issue.

Thanks.

**Comment by fabien-d** [comment]
Have you had any luck with this? I haven't been able to reproduce and if it's still an issue with the latest `0.3.10`?

**Comment by fabien-d** [comment]
Closing this issue - if it's still a problem feel free to reopen or open a new issue.
