### ISSUE TITLE
alertify-cover overlay DIV does not work on IE9.

### ISSUE THREAD

**Issue by MasNotsram** [fabien-d/alertify.js#141]
First let me say how fantastic Alertify is. It's such a nice simple replacement for the alert box that actually looks nice. Great idea.

On IE9 on Windows 7, the alertify-cover DIV is generated, but you can still click through it.

The fix is simple enough, I simply added onto the alertify-cover class in the CSS:

.alertify-cover {
background-color:white;
filter:alpha(opacity=0);
opacity:0;
}

However, it's probably worth adding this to the code.

Thanks again for the great JS.

**Comment by fabien-d** [comment]
Thanks for the report/fix. Would you mind opening a PR?

**Comment by fabien-d** [comment]
Fixed with ^ PR

**Comment by jheliker** [comment]
I am a new user of Alertify. I love it! Wanted to update the above CSS, as the opacity setting is not cross-browser compatible and won't work for partial opacity. Here is the class I am using, with 65% opacity:

.alertify-cover {
  position: fixed; z-index: 99999;
  top: 0; right: 0; bottom: 0; left: 0;
  background-color: white;
    /\* IE 8 _/
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=65)";
  /_ IE 5-7 _/
  filter: alpha(opacity=65);
  /_ Netscape _/
  -moz-opacity: 0.65;
  /_ Safari 1.x _/
  -khtml-opacity: 0.65;
  /_ Good browsers */
  opacity: 0.65;
}

Thanks to friends @ http://css-tricks.com/snippets/css/cross-browser-opacity/ for the browser opacity compatibility information.
