### ISSUE TITLE
Make the confirmation pop up fly on top of a div

### ISSUE THREAD

**Issue by AboOmar** [fabien-d/alertify.js#142]
Hey, great work AWESOME plugin,

But I need some simple requests, how it can be done ?

If you take a look inside Outloo.com e-mail client when you click on delete button a very small div (contains Yes or No) fly with very simple fade and slide under or above the clicked button ask the user to take action, Can this feature applied ?

Another request Is there any METRO theme for this plugin ?

Regards :)

**Comment by fabien-d** [comment]
There is no Metro theme with the plugin, but it would just be creating a new theme in CSS. I'll accept a PR! 

I don't have an outloook account, I sort of understand the request, which would require quite a bit of tweaking - but could you provide a screenshot just to confirm.

**Comment by AboOmar** [comment]
o.k, thanks my friend

![image](https://f.cloud.github.com/assets/1265037/677796/57c700fe-d924-11e2-8f49-693499f807c5.png)

as you can see in this screenshot, when I clicked the button cancel, this little pop-up comes from top to down with little cool sliding animation, ask me to cancel or not.

So what do you think of initializing the plugin on specific DOM element, after that the pop-up appears on top of or bottom from the clicked element with a cool sliding animation :+1: 

Another issue, I am actually didn't remember itis implemented or not with alertify confirm, is to alow me disable any interaction on my screen elements through event or something like that, because the message appears but I can still click any element on the page.

Thanks :)

**Comment by fabien-d** [comment]
Initializing on a specific DOM element would require some tweaking. I can mark it as a nice to have or accept a PR if anyone wants to implement.

Clicking through is a [known issue](https://github.com/fabien-d/alertify.js/issues/141). There is a fix in the issue details, which I will implement soon.
