### ISSUE TITLE
old notifications not hiding 

### ISSUE THREAD

**Issue by itrn0** [fabien-d/alertify.js#143]
Old alerts not hidding (or hiding, but take their place).
Not always.

Browser: Google Chrome 27.0.1453.110
Alertify 0.3.9

![2013-06-13 16 48 03](https://f.cloud.github.com/assets/4687843/647902/530caaa8-d417-11e2-92fc-23f8eae19d97.png)

-------------------------------------------------- HTML CODE ---------------------------------------------------
&lt;div id=&quot;alertify-cover&quot; class=&quot;alertify-cover alertify-cover-hidden&quot;&gt;&lt;/div&gt;
&lt;section id=&quot;alertify&quot; class=&quot;alertify alertify-hidden&quot;&gt;&lt;/section&gt;
&lt;section id=&quot;alertify-logs&quot; class=&quot;alertify-logs&quot;&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide alertify-log-hide alertify-log-hide alertify-log-hide alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;article class=&quot;alertify-log alertify-log-error alertify-log-show alertify-log-hide&quot;&gt;ERROR_INVALID_EMAIL&lt;/article&gt;
&lt;/section&gt;

Sorry for my bad English.

**Comment by fabien-d** [comment]
Could you try the [demo page](http://fabien-d.github.io/alertify.js/) with the same browser? Generally this issue happens when the browser supports `transitionend` but the event is not firing properly.

If the issue can be reproduced on the demo page, I'll try to debug, if it doesn't happen on the demo page, maybe you could provide a code sample from your project so I can take a look.

**Comment by fabien-d** [comment]
any updates on this?

**Comment by fabien-d** [comment]
Closing this issue - if it's still a problem feel free to reopen or open a new issue.

**Comment by EmmanuelVella** [comment]
Same issue here with Chrome 34.0.1847.116. This seems to happen when notifications are created when the website tab is not visible.
