### ISSUE TITLE
Confirm Box OK should submit the form

### ISSUE THREAD

**Issue by gouthamsworld** [fabien-d/alertify.js#144]
Hi,

I am having trouble with the confirm box.
I can see the pop coming up but when i click OK i want to Submit the form and when i click cancel it should do nothing

```
    $(function () {
        $("#Button1").on("click", function () {
            var s = alertify.confirm("This is an alert dialog");
            if (s == true) {
```

// I tried writing Fornname.Submit but dint work
                }
                else { return  false }
            });

```
    });
```

**Comment by fabien-d** [comment]
The alertify confirm method does not work the same as the native confirm. It does not return true or false. JavaScript is non-blocking meaning the `if (s == true) {` will get tested before the user clicks on ok or cancel.

alertify uses callbacks to get around this problem...

``` js
$("#Button1").on("click", function () {
    alertify.confirm("This is an alert dialog", function (e) {
        if (e) {
            // user clicked ok
        } else {
            // user clicked cancel
        }
    });
});
```

**Comment by gouthamsworld** [comment]
It worked thanks !!!
But the button click event on the server side is not being fired after clicking OK though the form is being submitted
.

  $(function () {

```
        $("#Button1").on("click", function () {
            alertify.confirm("This is an alert dialog", function (e) {

                if (e) {
                    $('#form1').submit();

                } else {
                    return false;
                }
            });
            return false;
        });



    });
```

**Comment by fabien-d** [comment]
sorry for the delay - any progress on this? If not, any chance you could provide more info on the issue. I'm not sure what you mean by

> button click event on the server side is not being fired.

**Comment by gouthamsworld** [comment]
$(function () {

```
    $("#Button1").on("click", function () {
        alertify.confirm("This is an alert dialog", function (e) {

            if (e) {
                $('#form1').submit();

            } else {
                return false;
            }
        });
        return false;
    });



});
```

on the server-side i have 

Public Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click

//Do something

End Sub

this event is not being fired after i click OK on the alertify

**Comment by fabien-d** [comment]
Closing this issue - if it's still a problem feel free to reopen or open a new issue.
