### ISSUE TITLE
If alert / confirm box is triggered by an enter key, it breaks.

### ISSUE THREAD

**Issue by dazbradbury** [fabien-d/alertify.js#16]
OK, so I have some alerts that appear after a user types in some text, and presses submit.

However, if rather than click submit, they press enter, the keydown event is captured by Alertify, and then processed.

The effect is like enter is pressed twice. Once to bring up the alert, and then to "OK" it. 

This only happens once the alert html has been created (ie. setup has been actioned), and alertify has bound the keydown event. Hence, it will only occur after the second attempt of trying.

**Comment by fabien-d** [comment]
Resolved with ^ pull request.
