### ISSUE TITLE
<a> tag clickable area becomes extra thin after confirm/prompt

### ISSUE THREAD

**Issue by dimorozov** [fabien-d/alertify.js#162]
You can reproduce it on your home page http://fabien-d.github.io/alertify.js
- Scroll your page to "default dialogs" section
- Click on "Prompt dialog" link. Cancel or Ok the dialog
- Scroll your page so that "Alert Dialog Confirm Dialog Prompt Dialog" line stays at the top of the page
- Hover on the "Prompt dialog" link
- Observe that you can't see the clickable area of the link anymore.
  Also I somehow managed to break the style of the dialogs so it looks like this:
  http://imgur.com/k7szYFS and I really don't know how to restore it. I tried refreshing the page, clearing the cache etc

**Comment by fabien-d** [comment]
Both issues were fixed with `0.3.10`. I just forgot to update the version of alertify.js on the demo page.

Tied to #146.

**Comment by dimorozov** [comment]
Thank you! Works great now!
