### ISSUE TITLE
Problem with prompt on iOS

### ISSUE THREAD

**Issue by gschrader** [fabien-d/alertify.js#163]
I built the latest code (0.3 had an unrelated issue so I can't use that) and am having issues with prompts (iPhone breaks, iPad seems to be ok, Safari/Chrome desktop seems fine).

If I enter a value and either hit go on the iOS keyboard or hit the OK (alertify) dialog button, the keyboard remains visible (even though the dialog and text field are gone) and the body ends up being disabled.  I try touching some of my elements my callback ends up being called again.

Hopefully I've described this ok let me know if I'm not making any sense.

**Comment by gschrader** [comment]
Played a bit more with this.  If I hit done to hide the keyboard in the input field and then hit the alertify ok button, I get the same locked up behaviour, I don't get the weird extra callbacks though :confused:

**Comment by fabien-d** [comment]
Is this only happening with the `master` branch (release `0.4.*`)?

The `0.4` is only a release candidate so bugs are to be expected. I will listed as an 0.4 bug and look at it for the next RC.

What was the unrelated issue with 0.3?

**Comment by gschrader** [comment]
Yes from master (I also tried the 0.4.0rc1 tag).

The issue in 0.3 was if you use enter to submit from the dialog (or in iOS the go button) it would still treat it as cancelled, so you could only use the OK alertify button.  This occurs on the demo page right now. This seems to be ok in 0.4.

**Comment by lexoyo** [comment]
hello
any news about this issue?
thank you :)

**Comment by fabien-d** [comment]
I'll be looking at why this is happening in `0.3.*`. I'm getting close to releasing the next [version of alertify - 0.5.0](https://github.com/fabien-d/alertify.js/tree/wip.0.5.0) and this issue has been resolved.

I'll look into backporting to `0.3.*`

**Comment by fabien-d** [comment]
Fixed with ^. Will be part of `0.3.11`

**Comment by lexoyo** [comment]
great!!
will we be notified of the new version? on github?

On Tue, Oct 8, 2013 at 2:27 AM, Fabien Doiron notifications@github.comwrote:

> Fixed with ^. Will be part of 0.3.11
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fabien-d/alertify.js/issues/163#issuecomment-25856646
> .

## 

Alex Hoyau
+33 (0) 6 76 68 38 06
http://lexoyo.me
Recevoir les news de Silex Labs par mail
http://eepurl.com/F48q5

**Comment by fabien-d** [comment]
Available now: 
- Source code: https://github.com/fabien-d/alertify.js/releases/tag/0.3.11 or
- Install via bower: `bower install alertify.js` (note this was previously `alertify`)

I will be updating the demo page and docs shortly.

**Comment by fabien-d** [comment]
Closing

**Comment by lexoyo** [comment]
Great, it works, thank you!
I have included alertify.js in Silex
https://github.com/silexlabs/Silex
