### ISSUE TITLE
Suggestion: Options for multiple buttons

### ISSUE THREAD

**Issue by davistan** [fabien-d/alertify.js#164]
Hi Fabien, it would be great if we could have more buttons (maybe up to 5?) as following:

```
alertify.buttons([
  { id: 'ok', label: 'Accept', default: true, focus: true },
  { id: 'deny', label: 'Deny' },
  { id: 'later', label: 'Later', cancel: true }
])
```

The order of the array is order of the buttons from left to right. Then we can also use it in below, which also improve code readability:

```
alertify.prompt("message", function(e, n) {
    if (e === 'ok') { 

    }
    else if (e === 'later') {

    }
})
```

What do you think?

**Comment by fabien-d** [comment]
The goal of the project is to mimic native dialogs. Adding multiple buttons would go against this.

Closing this issue - if you want to have more discussion feel free to reopen or open a new issue.
