### ISSUE TITLE
Spacebar triggers "ok" button. Prevent this

### ISSUE THREAD

**Issue by MrWeb** [fabien-d/alertify.js#165]
I tried to look for an answer to this but I found only one answer and this was later on closed and couldn't see a solution.

The point is that I load thru ajax a page and show it inside alertify.confirm, this way:

$('.add-faq').click(function(e){
        e.preventDefault();
        var sel_lang = $(this).attr('data-lang');
        alertify.set({ labels: { ok: 'Salva', cancel : 'Annulla' } });

```
    $.ajax({
        url: base_url()+'admin/faqAddLayout',
        type: 'get',
        dataType: 'html',
        success: function(html) {

            alertify.confirm(html);

       }
    });
});
```

The page loaded in the prompt modal contains input fields. I need to remove the spacebar function as this doesn't help in this case.

**Comment by jalperin** [comment]
Did you ever figure this out @MrWeb ? I wish to achieve the same effect: disable the spacebar on the "ok" button.

**Comment by dhardtke** [comment]
You can remove the code or change the keycode to something that doesn't exist..

``` javascript
SPACE:32
```

change this to

``` javascript
SPACE:999
```

and it should work (not tested).

**Comment by jalperin** [comment]
That certainly works. I actually removed that ,SPACE:32 from the keys array. Thanks!
