### ISSUE TITLE
Cannot display 2 dialog boxes back to back

### ISSUE THREAD

**Issue by cscalfani** [fabien-d/alertify.js#166]
If from the callback of an alert dialog box, I trigger a process that brings up another dialog box, the second will display and then hide instantly.

This is because the first one didn't finish hiding. If there was a callback or event when transitionDone is called, then I wouldn't have to kludge my code with a 300ms delay. (I chose 300ms since the transition lasts 250ms.)

**Comment by chris03** [comment]
I'm having the same issue.

Doing a simple confirm followed by an alert is working: http://jsfiddle.net/QgEpN/2/

But when I do a confirm then an ajax call and then show an alert if does not work: http://jsfiddle.net/QgEpN/1/

**Comment by fabien-d** [comment]
Fixed with ^. Will be part of `0.3.11`

**Comment by fabien-d** [comment]
Available now: 
- Source code: https://github.com/fabien-d/alertify.js/releases/tag/0.3.11 or
- Install via bower: `bower install alertify.js` (note this was previously `alertify`)

I will be updating the demo page and docs shortly. Closing
