### ISSUE TITLE
alertify 0.4.0rc1: in Chrome 29 the browser window is scrolled down while showing confirmation dialog with button focus set to none

### ISSUE THREAD

**Issue by wiktorkowalczuk** [fabien-d/alertify.js#167]
Steps to reproduce:
1. Set dialog button focus to "none": Alertify.dialog.buttonFocus = "none";
2. Call the confirmation dialog.

Result: Chrome 29 (29.0.1547.57 m, Windows) scrolls the browser page half way down upon finishing the CSS transition.

Possible reason: the setFocus function is called upon finishing the transition. setFocus tries to call "focus()" on the focus element. In case the buttonFocus is set to "none", such element is an empty &lt;a&gt; element: &lt;a href='#' id='buttonFocuss' class='alertify-hidden'&gt;&lt;/a&gt;. Even though it has "alertify-hidden" class on it, it's not actually hidden, thus trying to focus it leads to this weird behavior. The simplest fix was to apply "display:none" to the "alertify-hidden" class, but this might be something to be fixed in the sources.

**Comment by fabien-d** [comment]
Closing this issue - `0.4` is deprecated, if it's a problem in `0.3` feel free to reopen or open a new issue.
