### ISSUE TITLE
alertify 0.4.0rc1: Confirmation dialog stays visible (but transparent) in the very top of the page once closed

### ISSUE THREAD

**Issue by wiktorkowalczuk** [fabien-d/alertify.js#168]
After calling the confirmation dialog and selecting either of the options, the dialog is hidden, but it remains in the top of the page at a fixed position; even though it's transparent, you can't click through it. The reason is in the CSS: in alertify 0.3.x we have the following rule:

:root \* > .is-alertify-dialog-hidden 
{
  display: block; 
  visibility: hidden;
}

In alertify 0.4.0rc1 the "visibility: hidden" property is removed, thus making the dialog remain on top of the content. It is advised to either return the "visibility: hidden" property to the mentioned CSS rule, or to replace it with "z-index:-1"

**Comment by giiska** [comment]
+1

**Comment by fabien-d** [comment]
Closing this issue since `0.4` is deprecated
