### ISSUE TITLE
Included Bootstrap Theme Doesn't Inherit

### ISSUE THREAD

**Issue by reustle** [fabien-d/alertify.js#169]
The alertify.bootstrap.css theme doesn't actually inherit anything from bootstrap, its just skinned to look like stock bootstrap. It would be nice if it inherited the developers existing bootstrap theme (eg button styles).

**Comment by chesedo** [comment]
I would also like to see a alertify.bootstrap.js rather than the css to allow inheritance. I am developing something that uses a green bootstrap theme and the default blue just looks out of place with it.

**Comment by fabien-d** [comment]
I don't intend on making it a full bootstrap module. If someone wants to fork it and develop/maintain it - that's great! I'll link to it. But the main repo will remain a stand alone widget. I don't want to tie it to any framework in any way. 

The bootstrap CSS was to show that it could easily be made to look and fit in a bootstrap project with little effort.

**Comment by chesedo** [comment]
It seems to me that alertify is written in pure javascript, so things like extending of jquery(plugin options) won't be possible, right?

Also is everything rendered from a template(variables) or will I have to change that if I were to fork it to make it fit any framework by just editing the template?

**Comment by fabien-d** [comment]
Closing this issue - if it's still a problem feel free to reopen or open a new issue.
