### ISSUE TITLE
Prevent events from propagating when input into the text field

### ISSUE THREAD

**Issue by charleslaw** [fabien-d/alertify.js#170]
If there is a prompt up, it would be nice to prevent keyboard inputs from propagating to the page below.

I have a prompt come up in a game i'm writing and the keys pressed to input some text in the prompt are causing events in the game.

**Comment by dionisis84** [comment]
Same problem here as mentioned above...!

**Comment by fabien-d** [comment]
And could you confirm this is with alertify.js `0.3.*`...

**Comment by charleslaw** [comment]
Oo, sorry for the bad label.  I'm using 0.4.0rc1

**Comment by dionisis84** [comment]
+1!! 0.4.0rc1

**Comment by fabien-d** [comment]
I'm closing this since `0.4` is deprecated. If it happens with `0.3` or `0.5wip` then feel free to reopen or log a new issue
