### ISSUE TITLE
Blocking page when came back from new opened tab

### ISSUE THREAD

**Issue by Alex-Sokolov** [fabien-d/alertify.js#177]
I use alertify.js 0.3.10 in case, where we check if user fill all inputs, and if not - ask if he really want to download file anyway with empty parameters. Link opening in new tab.
When we click `Download file` new tab open, file downloading. But when we back to page - it absolutely unuseful, because `#alertify-cover` block all clicks

``` js
function downloadFile(event) {
    event.preventDefault();
    window.open($(this).attr('href'));
}

$('#ref_table').on('click', '.link-class', function (event) {
    event.preventDefault();
    var $this = $(this);

    alertify.set({
        buttonReverse: true,
        buttonFocus: "cancel",
        labels: {
            ok: "Download file",
            cancel: "Return to form"
        }
    });

    alertify.confirm("Not all filled, download anyway?", function(e) {
        if (e) {
            alertify.log('Starting download...');
            downloadFile();
            $this.trigger('click');

            // Without that string when came back page broken
            $('#alertify-cover').addClass('alertify-cover-hidden');
        }
    });
});
```

Another div's adding hidden-classes ok, except this

**Comment by wizonesolutions** [comment]
@fabien-d  Is this fixed in `0.3.11`? The `visibility: hidden` tweak, etc.

**Comment by fabien-d** [comment]
@Alex-Sokolov I haven't been able to reproduce this - any chance you could put a demo together recreating (as basic as possible) the issue.

I tried including a `window.open` in a `alertify.confirm` and after closing the new window and going back to the original page, the dialog was gone and the page was fully usable.

If you can't provide a demo, any chance you can provide more info? Browser/OS, does it still happen with `0.3.11` ...

---

@wizonesolutions, the `0.3.11` fix was for back to back dialogs using AJAX https://github.com/fabien-d/alertify.js/issues/166 - not this one.

**Comment by Alex-Sokolov** [comment]
Hmm... seems that all work with 0.3.11!

**Comment by wizonesolutions** [comment]
This wasn't fixed for me in `0.3.11`, for what it's worth. I used the suggested CSS fix in my own styles, which did work (and it isn't hacking the script, so I will probably just forget about it and leave it :))

**Comment by fabien-d** [comment]
@wizonesolutions: could you put a demo together that reproduces the error?

**Comment by wizonesolutions** [comment]
Probably not easily — I didn't delve that deep, just found a CSS fix here and applied it. The app that was showing it has it fixed now. So I am OK with this just staying closed or being addressed when somebody can provide a more concrete example.
