### ISSUE TITLE
ReferenceError: alertify is not defined using backbone and requireJS

### ISSUE THREAD

**Issue by mstafkmx** [fabien-d/alertify.js#183]

**Comment by fabien-d** [comment]
Can you provide more info? A demo page, code samples...

**Comment by mstafkmx** [comment]
I am using backbone and RequireJS.
colectores.js:
define([], function () {
    jQuery.support.cors = true;
    $(document).ready(function () {
        console.log("colectores.js loaded");
        alertify.success("Hi");
    });
});
I have tried to use alerify en others files, but it not works.I load alertify using requireJS

**Comment by fabien-d** [comment]
the library detects if `define` is used and doesn't expose `alertify` globally. If you want to use with AMD, you need to include it as a dependency:

``` js
define( [ PATH_TO_ALERTIFY ], function ( alertify ) {
    alertify.success( 'Hi' );
} );
```

**Comment by mstafkmx** [comment]
Thanks Fabian.
Tengo otro error. la notificación sale en el fondo de la página pero no desparece.
I'm using css for bootstrap.
![alertify1](https://f.cloud.github.com/assets/2950990/1358882/a6e4e056-37d0-11e3-8cf9-dd0e99ff0bf3.png)

**Comment by fabien-d** [comment]
did you also include the `alertify.core.css`? you need both the core and theme styles.

**Comment by mstafkmx** [comment]
Thanks for your time. It works.

**Comment by fabien-d** [comment]
Great
