### ISSUE TITLE
Understanding log customization

### ISSUE THREAD

**Issue by persalena** [fabien-d/alertify.js#184]
I am sorry for the stupid question, it is about alertify.custom. 
In your examples I found only the following:

$("#custom").on( 'click', function () {
            reset();
            alertify.custom = alertify.extend("custom");
            alertify.custom("I'm a custom log message");
            return false;
        });

alertify.extend("custom") <-- what is 'custom' here? css class or something else? 
Where this parameter = "custom" declared? What this example exactly means?

**Comment by fabien-d** [comment]
not a stupid question - just bad documentation which I will try to update sometime.

The `extend` method allows to generate custom log messages. The parameter `custom` can be whatever you choose.

For example:

``` js
// sets a property on `alertify` object
alertify.[anyKeyValueYouWant] = alertify.extend( 'anyStringYouWant' );

// so you can then write
alertify.anyKeyValueYouWant( 'custom log message' );
```

In the HTML, this will output:

``` html
<!-- notice the extra class, this is the value passed in the extend method -->
<article class="alertify-log alertify-log-anyStringYouWant">custom log message</article>
```

Then in CSS, you can then control the look of those specific messages:

``` css
.alertify-log-anyStringYouWant {
    /* overwrite default styles */
}
```

In short:
- the string argument passed in the `extend` method will be used as a class name on the log messages
- the key value you assign to alertify lets you call it directly.

See https://github.com/fabien-d/alertify.js/wiki/0.3.*-API-Documentation#extend

This is how the `success` and `error` methods work - https://github.com/fabien-d/alertify.js/wiki/0.3.*-API-Documentation#success--error

Hope that's clear

**Comment by persalena** [comment]
Thank you for explanation! It is very helpful

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.
