### ISSUE TITLE
where in git can I find the .css files I need?

### ISSUE THREAD

**Issue by akarelas** [fabien-d/alertify.js#186]
I git cloned the repo, did a grunt build, but I can't find `.css` files anywhere, just `.scss` which aren't usable on my setup.

Please advise.

**Comment by fabien-d** [comment]
See https://github.com/fabien-d/alertify.js/issues/185#issuecomment-27147210

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.
