### ISSUE TITLE
no ending } in release 0.3.11

### ISSUE THREAD

**Issue by oste** [fabien-d/alertify.js#188]
I installed `"alertify.js" : "0.3.11"` via bower and I am seeing that there is no closing } at the bottom of `alertify.default.css`, I am currently using 0.3.10 which has a valid `alertify.default.css` file

**Comment by fabien-d** [comment]
Can you double check if this is not just indentation? I generally write CSS with sub styles nested. E.g.

``` css
.container {
}

    .container-child {
    }
```

which can make it seem like the last line is missing a closing `}` although it is not.

**Comment by oste** [comment]
ya, I am sure. I am actually importing the file into a less document with
@import (less) "default.css" and less has a compile error. Double checking
the file and it has a bunch of null values at the end with no ending }

On Wed, Oct 30, 2013 at 8:51 AM, Fabien Doiron notifications@github.comwrote:

> Can you double check if this is not just indentation? I generally write
> CSS with sub styles nested. E.g.
> 
> .container {}
> 
> ```
> .container-child {
> }
> ```
> 
> which can make it seem like the last line is missing a closing } although
> it is not.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fabien-d/alertify.js/issues/188#issuecomment-27386025
> .

## 

Regards,
Mike

**Comment by fabien-d** [comment]
Here's the file from that release tag: https://github.com/fabien-d/alertify.js/blob/0.3/themes/alertify.default.css. I don't see any missing `}`.

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.
