### ISSUE TITLE
alertify is not defined

### ISSUE THREAD

**Issue by johnny9028** [fabien-d/alertify.js#189]
Hello,
I have a login.php page that i include into the main index page. In the login.php i setted up an alertify.alert('username or pass is wrong') in case of...well...figure when. the problem is that my console keeps spitting "Uncaught ReferenceError: alertify is not defined'. It works fine if i put a random alertify.alert directly into the index tho. 
Any ideas?

**Comment by fabien-d** [comment]
I'm going to need more information.. code sample? This error only happens if the JS file hasn't been included.

**Comment by johnny9028** [comment]
i managed to get it running by adding window.onload before. however, is not the prettiest solutin but it seems to work :)
