### ISSUE TITLE
Demo page is broken (503)

### ISSUE THREAD

**Issue by taitems** [fabien-d/alertify.js#191]
Error page attached:

![image](https://f.cloud.github.com/assets/234593/1528076/281c1e4c-4c02-11e3-95a6-235d64c1bfc6.png)

**Comment by fabien-d** [comment]
It's a GitHub page and a temporary issue with them.

**Comment by taitems** [comment]
Yep, seeing this everywhere now. My bad.

**Comment by fabien-d** [comment]
no worries.
