### ISSUE TITLE
Unable to call focus after alert

### ISSUE THREAD

**Issue by JohnPennington** [fabien-d/alertify.js#195]
if (TestCase > 1) {alertify.alert("Please make a choice for either Percent Off Subtotal."); document.EditForm.percent_off_subtotal.focus();  return false;}

The alertify alert comes up, but afterwards, it doesn't execute the focus(). The following "return false" does execute to stop the form submission, so this seems to be an issue with focus().  This code works fine with the standard alert box.

Thoughts?

**Comment by fabien-d** [comment]
JavaScript is non blocking which means alertify.js does not block the execution like standard dialogs. You would have to use callbacks to handle it.

Since it does not block the execution the code continues to run while the alert is shown causing the the focus to be overlooked.

``` js
if (TestCase > 1) {
    alertify.alert("Please make a...", function () {
        // this code is only called after the button has been clicked
        document.EditForm.percent_off_subtotal.focus();
    });
}
```

**Comment by JohnPennington** [comment]
Thanks.  Makes perfect sense.  Since alerts are used a lot in form 
validation, this might be a good thing to add to your examples.

John

**Comment by fabien-d** [comment]
Closing - if you need more help feel free to reopen or open a new issue.
