### ISSUE TITLE
Text-Align For Text Separate From Buttons

### ISSUE THREAD

**Issue by JohnPennington** [fabien-d/alertify.js#196]
I'm trying to figure out the best way to have the text in a box left justified with the buttons centered.  I see in the CSS that if I set .alertify-inner's text-align to left, the text moves to the left, but the buttons do as well.  Nothing I do with the buttons seems to get the buttons to center with the text left justified.  Is there a trick to this that doesn't require changing the javascript?

**Comment by fabien-d** [comment]
There is a `.alertify-message` class that can be used to left align just the message, if I understand correctly.

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.
