### ISSUE TITLE
How to make alertify work with <a> click events

### ISSUE THREAD

**Issue by mostafatalebi** [fabien-d/alertify.js#197]
Hello
I have set an anchor tag and then attache alertify to it. But I do not know how to make it work. Because when I click on the link, it goes to the page, and does not let the alertify to pop up a box. This happens because alertify does not block the javascript from executing when it pops a box. Unlike JS confirm().

I would grateful to have your help. thanks. Here is my code:

$(document).ready(function(){

```
$('.delete-page').on('click', function(event){
    alertify.confirm("Message", function (e) {
      if (e) {
          //
      } else {            
        return false; 
      }        
  });     
});
```

});

**Comment by fabien-d** [comment]
``` js
$(document).ready(function(){
    $('.delete-page').on('click', function(event){
        // add me, stop the default link from clicking
        event.preventDefault();

        alertify.confirm("Message", function (e) {
          if (e) {
              // use window.location and go to a->href
          } else {            
            return false; 
          }        
      });     
    });
});
```

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.

**Comment by TeeeeJay** [comment]
Dear Fabien hope you're great i tried to do that but didnt work coz i have an $id when a person clicks on the ahref tag it gets the id so i cant use the window.location:example
window.location= 'EditProfile.php?disapprove=$id';
thank you so much
