### ISSUE TITLE
alertify upon a bootstrap modal not working

### ISSUE THREAD

**Issue by orlleite** [fabien-d/alertify.js#204]
When I show the modal with `$('#test').modal('show');` and click to open the prompt `alertify.prompt( 'Prompt', function (e, str) {}, "" );`, they both appears, but the alertify can not be edited. And if I press ESC key, they both disappear.

http://jsfiddle.net/IrvinDominin/PC7k4

http://stackoverflow.com/questions/21461522/alertify-upon-a-bootstrap-modal-not-working

BTW, It is a nice project and it's helping me a lot. Thank you guys.

**Comment by fabien-d** [comment]
The div highlighted in the screenshot below covers the alertify dialog (higher `z-index`) and also has a `tabindex` of `-1`. If you simply remove the `tabindex` attribute you will be able to edit the alertify prompt.

![image](https://f.cloud.github.com/assets/747616/2491019/a2065efe-b1d6-11e3-8473-827a95357338.png)

Feel free to reopen if this does not solve your issue.

**Comment by fabien-d** [comment]
And I should have looked at the stackoverflow link before posting that -

**Comment by orlleite** [comment]
Fabien, thanks for your time. I could posted the info here too but I didn't.
