### ISSUE TITLE
Messages won't change after second request to alert.

### ISSUE THREAD

**Issue by ruyaoyao** [fabien-d/alertify.js#212]
When I tried to alert twice with different msgs, it will always catch the old one instead of newer one, and later I found it was the problem before dialog is gonna be built when sending queue array which should be empty first. It also happens when you have prompt and alert invoked in the same page.

Thank you.

line 410 
<code> 
  queue = []; // I added this line to clear the array to refresh the message.
  queue.push({type: type, message: message, callback: fn, placeholder: placeholder, cssClass: cssClass});
</code>

**Comment by fabien-d** [comment]
could you provide a sample recreating this issue? It would make debugging/fixing easier. Thanks

**Comment by ruyaoyao** [comment]
hey man, I am so sorry after looking the problem once more, 
I've noticed it was my mistake that I modified your code caused this glitch. I created a new function to allows alert to close after the time I set and hide the button. That's what happened.

Sorry again.

**Comment by fabien-d** [comment]
No problem!
