### ISSUE TITLE
alertify not defined

### ISSUE THREAD

**Issue by babaxx** [fabien-d/alertify.js#213]
Hello,

I develop a website in asp.net and I wanted to add alertify on it.
The problem is that I insert alertify.min.js (and the css core and default) and when I want to call alertify, I have an error saying "alertify is not defined".
It considers that alertify does not exist as if I had not inserted it in the page.

I guess there is something making a conflict but I don't know what...

For information, I use a scriptManager (it activates AJAX for ASP.NET) and I use many jQuery scripts.
Could it be the source of this problem?
I spent a lot of time on it, but I didn't find anything conclusive...

Can you help me please?

**Comment by jcoz1968** [comment]
I use it in aspnet all the time.  Try using the browser's developer tools JavaScript console you see if you see an exception.  

-----Original Message-----

**Comment by babaxx** [comment]
The error in the console is "alertify not defined".
It's like I don't put the script into the page... But when I look at the source code, it's there.

For example I made a simple html page with an alertify call at the loading. It works.
I copy-paste the exact same thing in my MasterPage, I have this message in the console…

**Comment by jcoz1968** [comment]
Maybe call page.header.databind in master page load event

**Comment by jcoz1968** [comment]
Also make sure your path is right if your child view is in a different folder.  For example use tilde instead of ../

**Comment by babaxx** [comment]
Thank you for your answers.

The point is that I'm sure of the path given though when I looked at the source code I clicked on the link to be sure.
I even tried to put the alertify source code directly in the page between script tags and… no changes…

**Comment by fabien-d** [comment]
I don't know much about .NET environments, but a few quick things to check -
1. Could there be another script that is interfering? If you remove all other JS files, does the problem remain?
2. Double and triple check the path
3. Are you using AMD (e.g. requirejs)? That would prevent `alertify` from getting attached to the `window` object causing it to be `undefined`.

**Comment by babaxx** [comment]
I found what was the source of the problem, but I don't really know why...

In my page I had jquery.mobile.customized.min.js.
As soon as I commented it, alertify worked...

**Comment by jcoz1968** [comment]
Good to hear you found it.
