### ISSUE TITLE
Alertify Confirm Dialog disappears

### ISSUE THREAD

**Issue by rpundlik** [fabien-d/alertify.js#215]
Hello All,

I have implemented confirm dialog using alertify. But the confirm dialog disappears in fraction of seconds before I can click on Cancel OR OK button. I am unable to click on any of the buttons. Why this is so ? How should i resolve this ?
Also, I want to callback method on server side.. how can i do that..

Have tested this in IE 8+, latest firefox and chrome browser. Issue occurs on every browser.

I am using this VS2012, framework 4.5

Regards,
Rohit

**Comment by fabien-d** [comment]
Are you able to reproduce the issue on the [example site](http://fabien-d.github.io/alertify.js/)?

And please see https://github.com/fabien-d/alertify.js/wiki/Opening-Issues to provide enough information to be able to get issues resolved in a timely manner.
