### ISSUE TITLE
TypeError: logElement is undefined

### ISSUE THREAD

**Issue by farkhan** [fabien-d/alertify.js#23]
Nice library! I added the JS file at the end of body.  When I run  `alertify.success("Deleted")`, I get this error in firebug:

```
TypeError: logElement is undefined
logElement.insertBefore(log, logElement.firstChild);
```

Looking through the source, I see `logElement = document.createElement("section")` but the section element is not created anywhere in the body.

Any ideas why?

**Comment by fabien-d** [comment]
Should be fixed with ^ pull request
