### ISSUE TITLE
prompt should give focus to input

### ISSUE THREAD

**Issue by philfreo** [fabien-d/alertify.js#3]
when prompt is fired, put the focus in the textbox

**Comment by fabien-d** [comment]
Thanks for submitting the issue. Fixed with ^ pull request.

**Comment by CIAvash** [comment]
I tested this on Firefox 17, it's not working. It works fine on Chromium and IE 10.

**Comment by fabien-d** [comment]
Thanks for the note, testing is high on the priority list at the moment...

**Comment by fabien-d** [comment]
Resolved with ^ pull request
