### ISSUE TITLE
prompt: prevent default is called after callback

### ISSUE THREAD

**Issue by abrkn** [fabien-d/alertify.js#35]
if the callback throws an error, prevent default is never called and the browser navigates

**Comment by abrkn** [comment]
``` javascript
alertify.prompt('name?', function(e, s) { throw new Error(s) })
```

**Comment by fabien-d** [comment]
Good catch. I'm wondering if it makes sense to keep  the same functionality and fix the browser navigation issue or move towards the native implementation of dialogs (no callbacks). There's no validation in native dialogs, it simply does its job and lets the code figure out what to do with it... 

e.g.

``` js
var string = alertify.prompt("name?");
// string equals the input value... 
// continue code

if (alertify.confirm("sure?")) {
// true
} else {
// false
}
```

This would make it resemble the native dialogs but would take away the benefits of callbacks and chaining.

**Comment by abrkn** [comment]
you cannot achieve the same functionality as the native alert. definitely continue doing it like you are now, just prevent default before calling the callback.

**Comment by fabien-d** [comment]
Fixed with ^^ pull request
