### ISSUE TITLE
Setting type and attributes for Prompt's input

### ISSUE THREAD

**Issue by CIAvash** [fabien-d/alertify.js#39]
It would be nice if we could set the input's type and some of its attributes, you can make use of HTML5's new input attributes and types:

Attributes:
1. autocomplete: for turning autocomplete on or off.
2. pattern: for restricting input, for examle, to only numbers or letters.

Types:
1. email
2. number
3. url
or other types.

https://developer.mozilla.org/en-US/docs/HTML/Element/Input

**Comment by abrkn** [comment]
-1, bloat

**Comment by fabien-d** [comment]
I'm with @abrkn. The prompt dialog is intended to access a value and pass it to a callback - nothing more, nothing less. It's the callbacks job to handle validation.

I'll leave issue open and hear other opinions, but at this time I'm not inclined to implement.

**Comment by CIAvash** [comment]
We can say the same for forms, we can validate them after submission, or we can do that with JavaScript, still, these features are added to HTML5. I just thought with this, it can be a modern prompt. Obviously it's not crucial.

At first, I wanted to open an issue for turning off the auto completion, because a prompt doesn't store values, but alertify's prompt does. Then I thought it could be part of a bigger feature. Should I open another issue for that, Since you're probably not going to implement it?

**Comment by fabien-d** [comment]
I'll leave the issue open as a discussion and if the features gets a lot of interest I will reconsider.

**Comment by dschwen** [comment]
Would be nice if there was an option to set the input to type="password" rather than type="text"

**Comment by dschwen** [comment]
Rather than patching the source (which I did before) I tried 
 `$('#alertify-text').attr('type','password');`
right after the prompt call, but it gives me the following error.
 `Error: type property can't be changed`
I guess I could switch the element out entirely, but given that a login box is a rather obvious use-case for the prompt I think it would not be "bloat" to add a corresponding option.

**Comment by dschwen** [comment]
`$('#alertify-text').replaceWith('<input type="password" id="alertify-text" class="alertify-text"/>');`
does the trick

**Comment by fabien-d** [comment]
I wouldn't say that a prompt dialog is a typical use-case for a login box. Not very secure. 

However, I'm considering adding an [HTTP Authentication dialog](http://www.httpwatch.com/httpgallery/authentication/). 

## Screenshot

![HTTPAuth](https://f.cloud.github.com/assets/747616/57245/c8d7bf02-5b40-11e2-8852-7165637a429d.png)
Screenshot below is from above link under example 10, by clicking `Display Image` button.

**Comment by dschwen** [comment]
That is a system dialog. As far as I can see there is no way to implement this in JavaScript in a _more_ secure way than your prompt box. If you assume an attacker has the ability to inject JS into your page you are screwed in any case.

**Comment by fabien-d** [comment]
I just don't like passwords getting passed around unencrypted.

The idea for the auth dialog would need to be flushed, but at first thought I'm seeing it tied to a form element. It wouldn't provide the login functionality, just a wrapper to point to an end point that would. That form could get be intercepted using JS to prevent post back.

Just thinking out loud, if I decide to implement an auth dialog in alertify, it needs to be flexible, easily extendible without adding unnecessary bloat.

**Comment by gschrader** [comment]
This would definitely be a nice to have, definitely not bloat at all.  On iPhone you can specify "tel" as the type and it will give you the numeric keypad instead of the full keyboard, very useful for numeric prompts.

**Comment by fabien-d** [comment]
I'm not opposed to adding types, still not convinced on attributes (that is getting into a lot of bloat) - but it may have to wait for the `0.4`. 

The way the prompt dialog API is setup already has 3 optional parameters and would have to be reworked. 

**From:**

``` js
prompt( text [, callback, value, classes ] );
```

**To:**

``` js
prompt( text [, callback, options ] );

// where options contains (variable names for demonstration):
options = {
    value: '',
    classes: '',
    type: ''
};
```

**Instead of:**

``` js
prompt( text [, callback, value, classes, TYPE ] );
```

and I don't want to change the API (to break existing functionality) within a minor release. The `0.4` is based on a very similar API but since it's a release candidate I don't have an issue updating it to reflect a better approach.

**Comment by fabien-d** [comment]
Closing this issue - it's been sitting for a long time
