### ISSUE TITLE
Cancel and OK buttons are the wrong way around

### ISSUE THREAD

**Issue by WilliamBZA** [fabien-d/alertify.js#41]
Standard in OSs seems to be OK on the left, Cancel on the right. alertify.js has it the other way around.

**Comment by hpshelton** [comment]
This is dependent on the OS. Mac OS X uses primary action (confirm) on the right, secondary action (cancel) on the left. Windows does the opposite. The library should presumably match the OS it's running on.

**Comment by fabien-d** [comment]
I agree this could be a nice feature since it would mimic the native dialogs - but from a user experience, I'd rather have consistency. The goal is to mimic the native dialogs as much as possible, but also aim to improve the user experience where possible.

I'll leave open for discussion - and see where this goes.

**Comment by thers** [comment]
I bet the agree or ok button always should be on the right side
and disagree or cancel on the left side, because, as i think, right side always represents "+" and left side "-" so if we okay with somewhat we are making plus to it mentally.

**Comment by stuartkeith** [comment]
Perhaps it could be configurable? Keeping the existing behaviour by default, so it doesn't break anything.

Then the developer can easily:
- Not worry about it, and use the default;
- Choose the order that they feel is appropriate for their project (they might be developing a site used mostly by Windows users and feel primary/secondary is the right choice);
- Write code that inspects the browser's user agent and selects the appropriate order;
- Allow the user to choose the order and save it as a preference.

I don't know if putting the user agent code into Alertify itself is a good idea (sniffing the user agent is opening a can of worms), but I don't see any downsides in a simple "reverse button order" boolean (or however you'd go about it).

**Comment by fabien-d** [comment]
I'm not opposed to the `reverse` option. It could be part of the `set` method.
e.g. `alertify.set({ buttonReverse: true });`

or even more specific
`alertify.set({ buttonOrder: 'win' });`, `alertify.set({ buttonOrder: 'mac' });`

Something along those lines. I'm opposed to adding the user agent sniffing code in alertify...

**Comment by thers** [comment]
@fabien-d i think `buttonReverse: true` would be enough.

**Comment by stuartkeith** [comment]
Yeah, I think buttonReverse is enough. It makes it clear what it does and you're not tying the behaviour to any particular OS.

**Comment by stuartkeith** [comment]
I quickly tried it out here: https://github.com/stuartkeith/alertify.js/commit/c8bdc0f4cb1272a7e538c0975414bb0c448ccae9

**Comment by fabien-d** [comment]
@stuartkeith looks good. I left a comment on 1 line... but if you want to open a PR for it, I'll merge

**Comment by fabien-d** [comment]
Closed with ^ pull request. Will be part of release 0.3.1.
