### ISSUE TITLE
Correct usage of the delay property

### ISSUE THREAD

**Issue by sneridagh** [fabien-d/alertify.js#46]
Hi,
I've been fiddling with the

```
alertify.delay = n; 
```

property, without success. Please, can you show me a real working example about how to modify the default delay value (and include it in the docs)?.

Thanks!

**Comment by fabien-d** [comment]
It's a regression, I've resolved the labels property earlier (https://github.com/fabien-d/alertify.js/pull/45), the same will be applied to the delay property.

For now, you can specify the wait parameter individually...

``` js
alertify.success("message", wait); // optional time in ms
```

**Comment by fabien-d** [comment]
Fixed with ^^ pull request
