### ISSUE TITLE
auto-alert

### ISSUE THREAD

**Issue by tjoozey** [fabien-d/alertify.js#47]
can this be automatically called and ran when someone navigates to the web page?

 how can that be done?

**Comment by fabien-d** [comment]
you can call any of the alertify methods (e.g. alert, confirm, log...) on page load. 

If you have a DOM ready function... e.g. jQuery

``` js
$(function() {
    alertify.alert("Test");
});
```

or you can load the library at the end of the html page and call it from there (inline script is not ideal - just for demonstration purposes).

``` html
    <script src="path_to_file/alertify.min.js"></script>
    <script>alertify.alert("test");</script>
</body>
```

**Comment by tjoozey** [comment]
i will:
1. push the files and folders to the cloud
2. put this script in my head tag:

$(function() { alertify.alert("Test"); });
1. that will work?

**Comment by tjoozey** [comment]
Any1?

---

From: Tyler Johnson tjohnson51503@att.net
To: fabien-d/alertify.js 
reply@reply.github.com

Sent: Wed, December 5, 2012 3:38:55 PM
Subject: Re: [alertify.js] auto-alert (#47)

i will:
1. push the files and folders to the cloud
2. put this script in my head tag:

$(function() { alertify.alert("Test"); });
1. that will work?

**Comment by tjoozey** [comment]
how do i use the dom-ready function, the second piece of code is non-working at the end.

**Comment by fabien-d** [comment]
it's hard to help with the information you're providing. It seems like you're looking for more help than just implementing this plugin.

If you linked the alertify.js file like option 2 from the comment above (and replace the path_to_file with the actual path to the image) it should work.

**Comment by toin0u** [comment]
@tjoozey You can try this otherwise... A very very simple exemple...

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Test alertifyjs</title>
    <link rel="stylesheet" href="http://fabien-d.github.com/alertify.js/assets/js/lib/alertify/alertify.core.css" />
    <link rel="stylesheet" href="http://fabien-d.github.com/alertify.js/assets/js/lib/alertify/alertify.default.css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js"></script>
    <script src="http://fabien-d.github.com/alertify.js/assets/js/lib/alertify/alertify.min.js"></script>
    <script>
        $(document).ready(function() {
            alertify.labels = { ok: "Jaaaa!", cancel: "Nej..." };
            alertify.prompt("Does this test works ?", function (e, str) {
                if (e) {
                    alertify.success(alertify.labels.ok);
                } else {
                    alertify.error(alertify.labels.cancel);
                }
            });
        });
    </script>
</head>
<body>
</body>
</html>
```

**Comment by fabien-d** [comment]
This hasn't had any activity in a while, closing.
