### ISSUE TITLE
CSS Hide Transition Not Used--But Should Be

### ISSUE THREAD

**Issue by glenselle** [fabien-d/alertify.js#56]
The log messages are currently just being removed from the DOM after they're displayed for the wait time, but there is no animation. But it looks as if the CSS has an alertify-hide class which would do the opposite of alertify-show class using CSS transitions, but it doesn't seem to be used right now.

**Comment by fabien-d** [comment]
The intention is to animate in/out. It's using CSS3 transitions so it requires a bit more logic to only remove the element after the transition is done.

I will be implementing using the `transitionend` event. The fallback for [browsers that don't support the event](https://developer.mozilla.org/en-US/docs/CSS/Using_CSS_transitions#Browser_compatibility) will simply remove the element right away - as it currently does.

**Comment by fabien-d** [comment]
resolved with ^ pull request. Will be part of 0.3.1
