### ISSUE TITLE
Alert not dismissing on 'ok' click

### ISSUE THREAD

**Issue by stickhandle** [fabien-d/alertify.js#68]
When I use alert dialog, the "ok" button appears to be clicked, but does not trigger the click event. On mouseclick down, i see the button itself disappear, revealing a small ok text  link. On mouseclick up, the button reappears. Clicking the button doesn't register the dismiss event, only clicking the button _exactly where the underneath text link_ is will register the dismiss event. I don't see this behaviour in the sample page :-(. I get the same issue with FF 16 and IE 8/9 on windows xp (i know ... its a work machine)

All JS disabled (except as below). Issue still present in: 
*FF16, IE8 on WinXP 
*FF17, IE10 on Win7
Works in Chrome on Win7.

My Code:

```
<html>
<body>
...
</body>
<script language="javascript">

function gotoButtonClick() {
    /* validate the mandatory fields */
    alertify.alert("Please enter Phone # and SIM Serial #", function () { 
        //after clicking OK
    });

}

</script>
<!-- JavaScripts -->
<script src="./js/alertify.min.js"></script>
</html>
```

Pics show what happened after alert slides in. 
*First pic shows mouse click-down on button - reveals small 'ok' text link. 
*Second pic shows mouse click-up - shows the button again, dialog is not dismissed
*ONLY when the button is clicked why hovering EXACTLY over the hidden 'ok' text link, is the alert dialog dismissed

![click_down_button](https://f.cloud.github.com/assets/1816149/22819/30fa0de4-4a14-11e2-8ea3-358b902b5f6d.jpg)
![click_up](https://f.cloud.github.com/assets/1816149/22820/311eb37e-4a14-11e2-8c31-5cff273049b0.jpg)

UPDATE

It was a clash with some custom css :-(

**Comment by fabien-d** [comment]
It almost sounds like a conflict... If possible, I'd say disable any other plugins or JavaScript just as a preliminary ruling out whether it's a conflict or not (since it can't be reproduce on the example site)

When all JS is removed except for alertify, if the issue is gone, it will come down to finding out where the conflict is occurring and if it's an issue with alertify or not.

If that doesn't solve the issue would you be able to provide more info, e.g. steps to reproduce, screenshots, anything that could help.

It's hard to debug an issue when it's unreproducible.

**Comment by stickhandle** [comment]
Fair enough -- i suspect you're right (conflict). I'm a backend guy ... new
to JS, but I should have suspected that myself.

**Comment by fabien-d** [comment]
If you need more info/help simply reopen or log a new issue... if it happens to be a conflict, if you could post info about it, it'd be helpful. It'd be nice to see if it's something that alertify could prevent...

**Comment by stickhandle** [comment]
will do.

**Comment by stickhandle** [comment]
Reopened. Issue persists when all other JS is removed.
OS: WinXP, Win7
FF: 16, 17
IE: 8, 10
(note: worked on Win7, Chrome)

# CODE (a button on the page calls the gotoButton() function)

<html>
...
<body>
...
</body>

<script language="javascript">
function gotoButton() {
    /* validate the mandatory fields */
    alertify.alert("Please enter Phone # and SIM Serial #", function () { 
        //after clicking OK
    });
}
</script>



<script src="./js/alertify.min.js"></script>

# </html>

Pics of what happened:
First pic: When alert slides down, click button. Pic is on down press of mouse click.
![click_down_button](https://f.cloud.github.com/assets/1816149/22743/398de624-4a0f-11e2-8e4c-8e74c4de9e36.jpg)
Second pic: Return state after mouse click up.
![click_up](https://f.cloud.github.com/assets/1816149/22746/40bf0950-4a0f-11e2-8d1f-c80d237b26c1.jpg)
If click is on the hidden 'ok' revealed under the button in first pic, then the alert is dismissed. Anywhere else in the button area, and it is not dismissed.

**Comment by stickhandle** [comment]
Reopened.
All JS except disabled except as below.
Issue presents on WinXP in FF16 and IE8, Win7 in FF17 and IE10. Does not present on Win7 in Chrome,

CODE

``` html
<html>
<body>
...
</body>
<script language="javascript">

function gotoSim() {
    /* validate the mandatory fields */
    alertify.alert("Please enter Phone # and SIM Serial #", function () { 
        //after clicking OK
    });

}

</script>
<!-- JavaScripts -->
<script src="./js/alertify.min.js"></script>
</html>
```

Result are shown in the 2 pictures:

Pic1
![click_down_button](https://f.cloud.github.com/assets/1816149/22785/5ce0455c-4a11-11e2-952a-27e37be3193d.jpg)

Pic2
![click_up](https://f.cloud.github.com/assets/1816149/22787/68fdacc6-4a11-11e2-8d57-1af6f37697b0.jpg)

After alert slides down, on mouse down-click, I see Pic1 (the button disappears leaving an off-center 'ok' text link). On mouse up-click the button returns as in Pic2. 

ONLY when i click the button in the exact same space as the hidden 'ok' text link does the alert get dismissed. Any other area of the button does not dismiss the dialog.

**Comment by stickhandle** [comment]
All JS disabled (except as below). Issue still present in: 
*FF16, IE8 on WinXP 
*FF17, IE10 on Win7
Works in Chrome on Win7.

My Code:

``` html
<html>
<body>
...
</body>
<script language="javascript">

function gotoButtonClick() {
    /* validate the mandatory fields */
    alertify.alert("Please enter Phone # and SIM Serial #", function () { 
        //after clicking OK
    });

}

</script>
<!-- JavaScripts -->
<script src="./js/alertify.min.js"></script>
</html>
```

Pics show what happened after alert slides in. 
*First pic shows mouse click-down on button - reveals small 'ok' text link. 
*Second pic shows mouse click-up - shows the button again, dialog is not dismissed
*ONLY when the button is clicked why hovering EXACTLY over the hidden 'ok' text link, is the alert dialog dismissed

![click_down_button](https://f.cloud.github.com/assets/1816149/22819/30fa0de4-4a14-11e2-8ea3-358b902b5f6d.jpg)
![click_up](https://f.cloud.github.com/assets/1816149/22820/311eb37e-4a14-11e2-8c31-5cff273049b0.jpg)

**Comment by stickhandle** [comment]
All JS disabled (except as below). Issue still present in: 
*FF16, IE8 on WinXP 
*FF17, IE10 on Win7
Works in Chrome on Win7.

My Code:

```
<html>
<body>
...
</body>
<script language="javascript">

function gotoButtonClick() {
    /* validate the mandatory fields */
    alertify.alert("Please enter Phone # and SIM Serial #", function () { 
        //after clicking OK
    });

}

</script>
<!-- JavaScripts -->
<script src="./js/alertify.min.js"></script>
</html>
```

Pics show what happened after alert slides in. 
*First pic shows mouse click-down on button - reveals small 'ok' text link. 
*Second pic shows mouse click-up - shows the button again, dialog is not dismissed
*ONLY when the button is clicked why hovering EXACTLY over the hidden 'ok' text link, is the alert dialog dismissed

![click_down_button](https://f.cloud.github.com/assets/1816149/22819/30fa0de4-4a14-11e2-8ea3-358b902b5f6d.jpg)
![click_up](https://f.cloud.github.com/assets/1816149/22820/311eb37e-4a14-11e2-8c31-5cff273049b0.jpg)

**Comment by stickhandle** [comment]
All JS disabled (except as below). Issue still present in: 
- FF16, IE8 on WinXP 
- FF17, IE10 on Win7

Works in Chrome on Win7.

My Code:
Pics show what happened after alert slides in. 
- First pic shows mouse click-down on button - reveals small 'ok' text link. 
- Second pic shows mouse click-up - shows the button again, dialog is not dismissed
- ONLY when the button is clicked why hovering EXACTLY over the hidden 'ok' text link, is the alert dialog dismissed

![click_down_button](https://f.cloud.github.com/assets/1816149/22819/30fa0de4-4a14-11e2-8ea3-358b902b5f6d.jpg)
![click_up](https://f.cloud.github.com/assets/1816149/22820/311eb37e-4a14-11e2-8c31-5cff273049b0.jpg)

**Comment by stickhandle** [comment]
can't seem to post something new ... so i updated my original comment

**Comment by fabien-d** [comment]
I still can't reproduce this in any browser on my mac (don't have access to a PC ATM)

A couple things:
1. I'd add a doctype - your page may be in quirks mode `<!doctype html>`
2. How are you calling the `gotoButtonClick` function? Maybe that's where the issue happens.

It's very strange, all the button styles are simply CSS

**Comment by stickhandle** [comment]
I inherited this code ... and I don't doubt its a local issue.

Top of page:

``` html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="cache-control" content="no-cache">
    <title>Dashboard</title>

    <link rel="stylesheet" type="text/css" media="screen"
href="./css/screen.css" />
</head>
```

In terms of the way the gotoButtonClick function is called, its on submit
of the surrounding form:

```
<FORM name="simCreateRepairForm" METHOD="POST"
ACTION="javascript:gotoButtonClick();" >
```

hmmm ... let me check that
