### ISSUE TITLE
Clicking edges of buttons doesn't work

### ISSUE THREAD

**Issue by rofrankel** [fabien-d/alertify.js#7]
In Chrome Version 24.0.1312.14 beta on Ubuntu, if I click very near the edge of a button like OK or Cancel, I get visual feedback as if I'd clicked the button, but the modal isn't dismissed.

**Comment by fabien-d** [comment]
I currently don't have access to Ubuntu - and I'm not fully clear on the issue you're having. Could you provide a screenshot(s)?

**Comment by rofrankel** [comment]
Not near a Ubuntu machine either right now, but I'll try to clarify:

1)  Click the topmost row of pixels of one of the buttons in a dialog.
2)  The button gives the visual impression of having been pressed.
3)  The modal is not dismissed.

This doesn't occur when clicking near the middle of the button, just at the edge.

**Comment by fabien-d** [comment]
I was able to recreate it - sort of ... If I click on the first pixel (top) of the button, it moves down by 1px (:active state) which most likely moves the hit state as well, so on release it's no longer on the button and the click doesn't get triggered.

I'll look at it some more -

**Comment by fabien-d** [comment]
Closing with ^ pull request will be part of release `0.4.0`

**Comment by fabien-d** [comment]
Moved to `0.3.5` release
