### ISSUE TITLE
alertify.confirm is not working for me......please advice.

### ISSUE THREAD

**Issue by vanamcsharp** [fabien-d/alertify.js#77]
function confirmDelete() {
            alert('Starting.......');
            alertify.confirm("This is a confirm box.", function (e) {
                if (e) {
                    alert('test ..  ' + e);
                    alertify.success("You've clicked '" + alertify.labels.ok + "'");
                    return true;
                } else {
                    alertify.error("You've clicked '" + alertify.labels.cancel + "'");
                    //$('#hdnDelete').val('false');
                    return false;
                }
            });
        }

**Comment by fabien-d** [comment]
Could you provide more info? I tried the same code on my end and it works properly.
1. Browser/OS it's happening?
2. How do you call the confirmDelete method?
3. Is there any other JS that could create a conflict?

**Comment by fabien-d** [comment]
Has this been resolved? Looking to close this issue.

**Comment by fabien-d** [comment]
Closing - If more help is required, reopen or log a new issue
