### ISSUE TITLE
Add class when alertify-logs is empty

### ISSUE THREAD

**Issue by johnsardine** [fabien-d/alertify.js#78]
The design I applied to the log list, contains paddings and it appears even when the log list is empty, I think i would be usefull to add a class for when the list is empty so that people can hide the log list and show when needed. Thank you

**Comment by fabien-d** [comment]
Never considered that use case. An extra class would be a viable option. 

A quick workaround, until a solution for all targeted browsers is available, is to use the `:empty` CSS selector [(browser support)](https://developer.mozilla.org/en-US/docs/CSS/:empty#Browser_compatibility).

``` css
.alertify-logs:empty {
    display: none;
}
```

**Comment by fabien-d** [comment]
Fixed with ^ pull request. Will be part of release `0.4.0`

**Comment by fabien-d** [comment]
Moved to `0.3.5` release
