### ISSUE TITLE
There's no (clean) way to get the element that's created

### ISSUE THREAD

**Issue by simonexmachina** [fabien-d/alertify.js#88]
I'd like to be able to have a spinner on an alertify message, but I need the DOM element in order to be able to attach things to it. There's no way to get the element that is created.

**Comment by fabien-d** [comment]
Do you mean log messages? And what exactly are you trying to do, add/pass custom HTML to a log message?

**Comment by fabien-d** [comment]
Close this - dup of #89. The dialog box is always the same - and can already be targeted. The log messages will be returned when issue #89 is resolved.
