### ISSUE TITLE
section#alertify blocks underlying content

### ISSUE THREAD

**Issue by helmutstrasser** [fabien-d/alertify.js#92]
If you click e.g. the button "Promt Dialog" alertify injects the DOM section#alertify. After clicking "Ok", the section persists in the DOM (just classes change to hidden). You are not able to click the button again, if its position is exactly underneath this section.

Reproduce: Open http://fabien-d.github.com/alertify.js/ , scroll the page so "Customizable Dialog Box" with those three buttons is quite below the header of the page. Click "Promt Dialog" and click "Ok" to close the popup. Be sure that the width of the browser meets a condition so that the "Promt Dialog" button is underneath the section#alertify. You can't click the button again.

**Comment by fabien-d** [comment]
Great catch! Resolved with ^ pull request
