### ISSUE TITLE
Return before prompt ?

### ISSUE THREAD

**Issue by Obiwan-Kennedy** [fabien-d/alertify.js#97]
Hello,

I try to override Javascript basic dialog boxes.
It works fine for the alert function.
But for the prompt function it doesn't work.

Here is my code :

```
var _oldprompt = window.prompt;
window.prompt = function()
{
    var _message ;
    var _position ;

    _message = arguments[0] ;
    alertify.prompt(_message, function(e, str)
    {
        if (e)
            return str ;
        else
            return null ;
    });
};
```

Then, I just call something like this elsewhere :

```
_answer = prompt("What's your favorite color ?")
```

In debug mode, I check that I return from this call before the prompt is displayed and, of course, _anwer is always null.
But the prompt is then well displayed and I can type a string and validate the dialog.

It is true with jQuery 1.4.2 and IE 8 or Firefox 17

Am I wrong somewhere ? Or is it a true issue ? Or just maybe a jQuery version issue (but currently, I can't upgrade) ?

Thanks.

Obiwan

**Comment by Obiwan-Kennedy** [comment]
OK ! If my code is not wrong, it seems to be an issue, not a jQuery version problem.
I have temporarily replaced my jQuery file with the lastest version. Same result, also encountered with the confirm dialog.

**Comment by dparlevliet** [comment]
Alertify doesn't rely on jQuery.

_answer will always be undefined in this code. _answer will be the result of whatever is returned from your prompt function.

```
window.prompt = function() { ... }
```

Which, in your case is nothing. Hence, undefined. I do not believe you can use alertify for the functionality that you are looking for in this instance because the very nature of JavaScript is non-blocking. However, Since you're using jQuery I recommend (actually I recommend other things, but this will do) using a bind which will achieve something close to it.

```
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="/js/plugins/alertify/themes/alertify.css">
  </head>
  <body>
    <script type="text/javascript" src="/js/plugins/jquery.min.js"></script>
    <script type="text/javascript" src="/js/plugins/alertify/lib/alertify.js"></script>
    <script type="text/javascript">
      var _oldprompt = window.prompt;
      window.prompt = function() {
        var _message ;
        var _position ;

        _message = arguments[0] ;
        alertify.prompt(_message, function(e, str) {
          $(document).trigger('prompt_callback', (e) ? str : null);
        });
      };
      prompt("What's your favorite color ?");
      $(document).one('prompt_callback', function(e, answer) {
        console.log(answer);
        prompt("Really, you like "+answer+"?");
        $(document).one('prompt_callback', function(e, answer) {
          alertify.log('OK! Werido.');
        });
      });
    </script>
  </body>
</html>
```

Note: the use of one() and not on(), this will help ensure your binds don't overlap.

###### Example for keeping yourself inside an object.

```
<script type="text/javascript">
  var _oldprompt = window.prompt;
  window.prompt = function() {
    var _message ;
    var _position ;

    _message = arguments[0] ;
    alertify.prompt(_message, function(e, str) {
      $(document).trigger('prompt_callback', (e) ? str : null);
    });
  };
  object = {
    initialize: function() {
      prompt("What's your favorite color ?");
      $(document).one('prompt_callback', this, this.callback);
    },
    callback: function(e, answer) {
      self = e.data;
      console.log(e, self, answer);
      prompt("Really, you like "+answer+"?");
      $(document).one('prompt_callback', self, self.callback2);
    },
    callback2: function(e, answer) {
      alertify.log('OK! Weirdo.');
    }
  }
  object.initialize();
</script>
```

**Comment by fabien-d** [comment]
@dparlevliet gave you good advice. I haven't tested the code, but it makes sense. For me, I would have asked why you wanted to do it this way? The only 2 things I can think of:
1. You don't like writing `alertify.` everytime, or you wish to replace all existing native dialogs without changing any of the code base.
2. You like that the native dialogs return a value  

``` js
alert(...)   // returns undefined
confirm(...) // returns true/false
prompt(...)  // returns input value/null
```

Both of which are very hard to deal with.

> because the very nature of JavaScript is non-blocking

This is it. A user can't interact with a piece of UI while the script is executing, so if a user has to interact with UI before the script finishes, and the script has to finish before the user can interact with the UI... the browser would hang.

This is why alertify is using callbacks. It ensures that the script is only executed after the interaction has been made, but it doesn't block the execution of the rest of the code.

I would consider changing the implementation and adding a `finally` function as a parameter. I'm not sure if it adds too much value, but could be worth exploring.

``` js
alertify.alert("string", fnYes, fnFinally);
alertify.confirm("string", fnYes, fnNo, fnFinally);
alertify.prompt("string", fnYes, fnNo, fnFinally); 
```

Above is very rough, but the `fnFinally` method would be called after the `fnYes` or `fnNo` to continue with your next code block.

**Comment by Obiwan-Kennedy** [comment]
Hey guys,

Thanks for your answers.

fabien-d, you got it ! (« You don't like writing alertify. everytime, or you wish to replace all existing native dialogs without changing any of the code base »)

dparlevliet, thanks for your advice. I'll try it, but first I need to understand it in details !
So, I'll dive into it immediately. Hope I'll be able to return to surface and breathe rapidly. ;-)

Obiwan

**Comment by pavanvusirika** [comment]
It would be very helpful if the prompt dialog is blocking by default.The problem is we can't replace the basic java script dialogs. If we wanted to do we need to write extra code like above every where, which is cumbersome.We were going to replace every prompt with alertify.js but because of this problem we dropped.Any way thanks.

**Comment by dparlevliet** [comment]
It's not possible. JavaScript is non-blocking by design. Also you could extend the code above to pass a callback, which would greatly minimize the amount of code you would have to change in your project. 

Maybe some more investigation is necessary before passing up on it completely.

**Comment by fabien-d** [comment]
As @dparlevliet mentioned, JavaScript is non-blocking by design. The idea that `alertify.` can simply be thrown in front of native dialog and everything just works is flawed.

I also get that it would be nice if it could, but it's just not possible. It's just a matter of separating the code a little bit.

Step 1: Current code

``` js
// using native dialogs
function init () {
    var answer = prompt("question");
    // do something with answer
}
```

Step 2: Separate the dialog from the rest of the code

``` js
// change to
function init () {
    var answer = prompt("question");
    handleAnswer(answer);
}

function handleAnswer (answer) {
    // do something with answer
}
```

Step 3: using alertify

``` js
// alertify 0.3.8
function init () {
    alertify.prompt("question", function (e, answer) {
        if (e) {
            handleAnswer(answer);
        }
    });
}

function handleAnswer (answer) {
    // do something with answer
}
```

``` js
// alertify 0.4.0rc1
function init () {
    Alertify.dialog.prompt("question", function (answer) {
        handleAnswer(answer);
    });
}

function handleAnswer (answer) {
    // do something with answer
}
```

**Comment by dparlevliet** [comment]
Just to follow up on this for anyone else that might stumble across it and want to achieve the same thing. If you're using underscore with something like Backbone and you want to be able to get back inside your object to do more events, this is an example of how you can achieve this.

```
window.confirm = function (message, callback) {
  alertify.confirm(message, callback)
}

var myobj = {
  method: function() {
     confirm('Are you sure?', _.bind(function(choice) {
        if (choice)
          this.follow_up_method();
      }, this));
  },
  follow_up_method: function(e) {

  }
};
```
